### ISSUE TITLE
Does not compile with the latest satori/go.uuid 1.2.0

### ISSUE THREAD

**Issue by dsolonenko** [epsagon/epsagon-go#13]
The issue is well known https://github.com/satori/go.uuid/issues/66, the consensus is to migrate away from the library.

**Comment by enoodle** [comment]
Thank you! I will try to see how to fix this soon.
In the mean time the Gopkg.lock has version 1.2.0 and the example is compiling, So I am guessing it is not working with version 2.0 or with applications requiring this version? (or maybe this tag changed since)

BTW if you wish to submit a fix you are welcome
